// Objective-C API for talking to github.com/2dust/AndroidLibXrayLite Go package.
//   gobind -lang=objc github.com/2dust/AndroidLibXrayLite
//
// File is generated by gobind. Do not edit.

#ifndef __Libv2ray_H__
#define __Libv2ray_H__

#import <Foundation/Foundation.h>
#include "ref.h"
#include "Universe.objc.h"


@class Libv2rayCoreController;
@protocol Libv2rayCoreCallbackHandler;
@class Libv2rayCoreCallbackHandler;

@protocol Libv2rayCoreCallbackHandler <NSObject>
- (long)onEmitStatus:(long)p0 p1:(NSString* _Nullable)p1;
- (long)shutdown;
- (long)startup;
@end

/**
 * CoreController represents a controller for managing Xray core instance lifecycle
 */
@interface Libv2rayCoreController : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewCoreController initializes and returns a new CoreController instance
Sets up the console log handler and associates it with the provided callback handler
 */
- (nullable instancetype)init:(id<Libv2rayCoreCallbackHandler> _Nullable)s;
@property (nonatomic) id<Libv2rayCoreCallbackHandler> _Nullable callbackHandler;
@property (nonatomic) BOOL isRunning;
/**
 * MeasureDelay measures network latency to a specified URL through the current core instance
Uses a 12-second timeout context and returns the round-trip time in milliseconds
An error is returned if the connection fails or returns an unexpected status
 */
- (BOOL)measureDelay:(NSString* _Nullable)url ret0_:(int64_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * QueryAllOutboundTrafficStats retrieves and resets all outbound traffic counters.
Returns a single-line text in format: tag,direction,value;tag,direction,value;
Returns an empty string if the stats manager is not initialized or no counters exist.
 */
- (NSString* _Nonnull)queryAllOutboundTrafficStats;
/**
 * QueryStats retrieves and resets traffic statistics for a specific outbound tag and direction
Returns the accumulated traffic value and resets the counter to zero
Returns 0 if the stats manager is not initialized or the counter doesn't exist
 */
- (int64_t)queryStats:(NSString* _Nullable)tag direct:(NSString* _Nullable)direct;
/**
 * StartLoop initializes and starts the core processing loop
Thread-safe method that configures and runs the Xray core with the provided configuration
Returns immediately if the core is already running
 */
- (BOOL)startLoop:(NSString* _Nullable)configContent tunFd:(int32_t)tunFd error:(NSError* _Nullable* _Nullable)error;
/**
 * StopLoop safely stops the core processing loop and releases resources
Thread-safe method that shuts down the core instance and triggers necessary callbacks
 */
- (BOOL)stopLoop:(NSError* _Nullable* _Nullable)error;
@end

/**
 * CheckVersionX returns the library and Xray versions
 */
FOUNDATION_EXPORT NSString* _Nonnull Libv2rayCheckVersionX(void);

FOUNDATION_EXPORT NSString* _Nonnull Libv2rayFetchQuicCertSha256(NSString* _Nullable requestJSON);

FOUNDATION_EXPORT NSString* _Nonnull Libv2rayFetchTlsCertSha256(NSString* _Nullable requestJSON);

/**
 * InitCoreEnv initializes environment variables and file system handlers for the core
It sets up asset path, certificate path, XUDP base key and customizes the file reader
to support Android asset system
 */
FOUNDATION_EXPORT void Libv2rayInitCoreEnv(NSString* _Nullable envPath, NSString* _Nullable key);

/**
 * MeasureOutboundDelay measures the outbound delay for a given configuration and URL
 */
FOUNDATION_EXPORT BOOL Libv2rayMeasureOutboundDelay(NSString* _Nullable ConfigureFileContent, NSString* _Nullable url, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * NewCoreController initializes and returns a new CoreController instance
Sets up the console log handler and associates it with the provided callback handler
 */
FOUNDATION_EXPORT Libv2rayCoreController* _Nullable Libv2rayNewCoreController(id<Libv2rayCoreCallbackHandler> _Nullable s);

/**
 * ReconcileBrowserDialer updates the browser dialer address and reloads its configuration
If the dialer address is empty, it will disable the browser dialer and close existing connections
 */
FOUNDATION_EXPORT void Libv2rayReconcileBrowserDialer(NSString* _Nullable dialerAddr);

@class Libv2rayCoreCallbackHandler;

/**
 * CoreCallbackHandler defines interface for receiving callbacks and notifications from the core service
 */
@interface Libv2rayCoreCallbackHandler : NSObject <goSeqRefInterface, Libv2rayCoreCallbackHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (long)onEmitStatus:(long)p0 p1:(NSString* _Nullable)p1;
- (long)shutdown;
- (long)startup;
@end

#endif
