name: iosApp
options:
  bundleIdPrefix: com.android.xrayfa
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Config.xcconfig
  Release: Config.xcconfig
targets:
  iosApp:
    type: application
    platform: iOS
    configFiles:
      Debug: iosApp.xcconfig
      Release: iosApp.xcconfig
    sources:
      - path: iosApp
        excludes:
          - Entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.android.xrayfa.ios
      INFOPLIST_FILE: iosApp/Info.plist
      CODE_SIGN_ENTITLEMENTS: iosApp/Entitlements/iosApp.entitlements
      PRODUCT_NAME: XrayFA
    dependencies:
      - target: PacketTunnel
        embed: true
    preBuildScripts:
      - name: Compile Kotlin Framework
        basedOnDependencyAnalysis: false
        script: |
          set -e
          cd "$SRCROOT/.."
          ./gradlew :shared:embedAndSignAppleFrameworkForXcode
    scheme:
      testTargets: []

  PacketTunnel:
    type: app-extension
    platform: iOS
    configFiles:
      Debug: PacketTunnel.xcconfig
      Release: PacketTunnel.xcconfig
    sources:
      - path: PacketTunnel
        excludes:
          - Entitlements
        includes:
          - "**/*.swift"
          - "**/*.m"
          - "**/*.h"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.android.xrayfa.ios.PacketTunnel
      INFOPLIST_FILE: PacketTunnel/Info.plist
      CODE_SIGN_ENTITLEMENTS: PacketTunnel/Entitlements/PacketTunnel.entitlements
      PRODUCT_NAME: PacketTunnel
      SKIP_INSTALL: YES
      LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks @executable_path/../../Frameworks
      SWIFT_OBJC_BRIDGING_HEADER: PacketTunnel/PacketTunnel-Bridging-Header.h

schemes:
  iosApp:
    build:
      targets:
        iosApp: all
        PacketTunnel: all
    run:
      config: Debug
