package com.android.xrayfa.shared.ui

import androidx.compose.runtime.Composable
import com.android.xrayfa.shared.navigation.ConfigFilterLabels
import com.android.xrayfa.shared.resources.*
import com.android.xrayfa.shared.ui.config.ConfigUiLabels
import com.android.xrayfa.shared.ui.config.EditUiLabels
import com.android.xrayfa.shared.ui.home.HomeUiLabels
import com.android.xrayfa.shared.ui.settings.RouteSettingsUiLabels
import com.android.xrayfa.shared.ui.settings.SettingsUiLabels
import com.android.xrayfa.shared.ui.subscription.SubscriptionUiLabels
import org.jetbrains.compose.resources.stringResource

@Composable
fun rememberHomeUiLabels(): HomeUiLabels =
    HomeUiLabels(
        connectedLabel = stringResource(Res.string.connected),
        disconnectedLabel = stringResource(Res.string.not_connected),
        connectedHint = stringResource(Res.string.tap_to_disconnect),
        disconnectedHint = stringResource(Res.string.tap_to_connect),
        uploadLabel = stringResource(Res.string.upload_data),
        downloadLabel = stringResource(Res.string.download_data),
        connectionDetailsHeader = stringResource(Res.string.connection_detail),
        unknownProtocolLabel = stringResource(Res.string.unknown),
        emptyNodeMessage = stringResource(Res.string.select_configuration_notify),
        configNotReadyMessage = stringResource(Res.string.config_not_ready),
    )

@Composable
fun rememberConfigFilterLabels(): ConfigFilterLabels =
    ConfigFilterLabels(
        manualLabel = stringResource(Res.string.import_manually),
        allLabel = stringResource(Res.string.config_filter_all),
        favoriteLabel = stringResource(Res.string.config_filter_favorite),
    )

@Composable
fun rememberConfigUiLabels(): ConfigUiLabels =
    ConfigUiLabels(
        title = stringResource(Res.string.config),
        manualFilterLabel = stringResource(Res.string.import_manually),
        allFilterLabel = stringResource(Res.string.config_filter_all),
        favoriteFilterLabel = stringResource(Res.string.config_filter_favorite),
        emptyTitle = stringResource(Res.string.no_configuration),
        emptyHint = stringResource(Res.string.no_configuration_hint),
        createConfigLabel = stringResource(Res.string.create_a_config),
        createNodeTitle = stringResource(Res.string.config_create_node),
        unknownProtocolLabel = stringResource(Res.string.unknown),
        timeoutLabel = stringResource(Res.string.timeout),
        testingLabel = stringResource(Res.string.config_testing),
        addToFavoritesLabel = stringResource(Res.string.add_to_favorites),
        removeFromFavoritesLabel = stringResource(Res.string.remove_from_favorites),
        testDelayLabel = stringResource(Res.string.test_url),
        shareLabel = stringResource(Res.string.clipboard_export),
        editLabel = stringResource(Res.string.edit),
        deleteLabel = stringResource(Res.string.delete),
        editNodeTitle = stringResource(Res.string.config_edit_node),
        nodeRemarkLabel = stringResource(Res.string.nick_name),
        nodeUrlLabel = stringResource(Res.string.config_node_url),
        saveLabel = stringResource(Res.string.save),
        cancelLabel = stringResource(Res.string.cancel),
        editNodeFailed = stringResource(Res.string.config_edit_node_failed),
        deleteNodeTitle = stringResource(Res.string.config_delete_node_title),
        deleteNodeConfirm = stringResource(Res.string.config_delete_node_confirm),
        speedTestAllLabel = stringResource(Res.string.config_speed_test_all_cd),
        locateSelectedLabel = stringResource(Res.string.locate_selected_node),
        deleteAllLabel = stringResource(Res.string.menu_delete_all),
        bugReportLabel = stringResource(Res.string.bug_report_header),
        searchLabel = stringResource(Res.string.apps_search),
        searchNoResultsLabel = stringResource(Res.string.config_search_no_results),
        deleteAllTitle = stringResource(Res.string.menu_delete_all),
        deleteAllConfirm = stringResource(Res.string.delete_notify),
    )

@Composable
fun rememberEditUiLabels(): EditUiLabels =
    EditUiLabels(
        editTitle = stringResource(Res.string.edit),
        addTitle = stringResource(Res.string.edit_add_title),
        backContentDescription = stringResource(Res.string.edit_back_cd),
        saveContentDescription = stringResource(Res.string.edit_save_cd),
        protocolSectionTitle = stringResource(Res.string.edit_protocol_section),
        basicSettingsTitle = stringResource(Res.string.edit_basic_settings),
        remarksLabel = stringResource(Res.string.edit_remarks),
        addressLabel = stringResource(Res.string.edit_address),
        portLabel = stringResource(Res.string.edit_port),
        protocolSettingsTitleFormat = stringResource(Res.string.edit_protocol_settings),
        uuidLabel = stringResource(Res.string.edit_uuid),
        encryptionLabel = stringResource(Res.string.edit_encryption),
        flowLabel = stringResource(Res.string.edit_flow),
        securityLabel = stringResource(Res.string.edit_security),
        passwordLabel = stringResource(Res.string.edit_password),
        methodLabel = stringResource(Res.string.edit_method),
        usernameOptionalLabel = stringResource(Res.string.edit_username_optional),
        passwordOptionalLabel = stringResource(Res.string.edit_password_optional),
        authLabel = stringResource(Res.string.edit_auth),
        sniLabel = stringResource(Res.string.edit_sni),
        alpnLabel = stringResource(Res.string.edit_alpn),
        obfuscationLabel = stringResource(Res.string.edit_obfuscation),
        obfuscationPasswordLabel = stringResource(Res.string.edit_obfuscation_password),
        allowInsecureLabel = stringResource(Res.string.edit_allow_insecure),
        transportSettingsTitle = stringResource(Res.string.edit_transport_settings),
        networkLabel = stringResource(Res.string.edit_network),
        wsPathLabel = stringResource(Res.string.edit_ws_path),
        wsHostLabel = stringResource(Res.string.edit_ws_host),
        grpcServiceNameLabel = stringResource(Res.string.edit_grpc_service_name),
        sniServerNameLabel = stringResource(Res.string.edit_sni_server_name),
        fingerprintLabel = stringResource(Res.string.edit_fingerprint),
        publicKeyLabel = stringResource(Res.string.edit_public_key),
        shortIdLabel = stringResource(Res.string.edit_short_id),
        noneOptionLabel = stringResource(Res.string.none).lowercase(),
    )

@Composable
fun rememberSubscriptionUiLabels(): SubscriptionUiLabels =
    SubscriptionUiLabels(
        title = stringResource(Res.string.menu_subscription),
        noSubscriptions = stringResource(Res.string.no_subscriptions),
        addSubscription = stringResource(Res.string.add_subscription),
        editSubscription = stringResource(Res.string.edit_subscription),
        nickName = stringResource(Res.string.nick_name),
        subscriptionUrl = stringResource(Res.string.subscription_url),
        preNode = stringResource(Res.string.pre_node),
        nextNode = stringResource(Res.string.next_node),
        none = stringResource(Res.string.none),
        cancel = stringResource(Res.string.cancel),
        confirm = stringResource(Res.string.confirm),
        delete = stringResource(Res.string.delete),
        edit = stringResource(Res.string.edit),
        subscribeFailed = stringResource(Res.string.subscribe_failed),
        duplicateMarkError = stringResource(Res.string.err_subscription_mark_duplicate),
        manageSubscriptions = stringResource(Res.string.menu_subscription),
        importFromClipboard = stringResource(Res.string.import_manually),
        shareSubscriptionUrl = stringResource(Res.string.share_subscription),
        subscriptionUrlCopied = stringResource(Res.string.copied),
        scanQr = stringResource(Res.string.scan_qr_title),
    )

@Composable
fun rememberRouteSettingsUiLabels(): RouteSettingsUiLabels =
    RouteSettingsUiLabels(
        title = stringResource(Res.string.route_settings_title),
        routingModeSectionTitle = stringResource(Res.string.routing_mode_label),
        routingModeGlobalLabel = stringResource(Res.string.routing_mode_global),
        routingModeRouteLabel = stringResource(Res.string.routing_mode_route),
        domainStrategySectionTitle = stringResource(Res.string.domain_strategy_section),
        domainStrategyAsIsLabel = stringResource(Res.string.domain_strategy_asis),
        domainStrategyIpIfNonMatchLabel = stringResource(Res.string.domain_strategy_ip_if_non_match),
        domainStrategyIpOnDemandLabel = stringResource(Res.string.domain_strategy_ip_on_demand),
        strategyFieldLabel = stringResource(Res.string.strategy_field),
        quickConfigSectionTitle = stringResource(Res.string.quick_config_presets),
        bypassChinaLabel = stringResource(Res.string.bypass_china),
        bypassChinaDescription = stringResource(Res.string.bypass_china_desc),
        proxyTelegramGoogleLabel = stringResource(Res.string.proxy_telegram_google),
        proxyTelegramGoogleDescription = stringResource(Res.string.proxy_telegram_google_desc),
        blockAdsLabel = stringResource(Res.string.block_ads),
        blockAdsDescription = stringResource(Res.string.block_ads_desc),
        customRulesSectionTitle = stringResource(Res.string.custom_routing_rules),
        addCustomRuleLabel = stringResource(Res.string.add_custom_rule),
        createCustomRuleTitle = stringResource(Res.string.create_custom_rule),
        ruleNameLabel = stringResource(Res.string.rule_name_tag),
        outboundTagLabel = stringResource(Res.string.outbound_tag),
        domainsLabel = stringResource(Res.string.domains_comma),
        ipsLabel = stringResource(Res.string.ips_comma),
        portLabel = stringResource(Res.string.port_example),
        confirmAddLabel = stringResource(Res.string.confirm_and_add),
        customRuleFallbackTitle = stringResource(Res.string.custom_rule_fallback),
        outboundTagShortLabel = stringResource(Res.string.outbound_tag_short),
        domainsPrefix = stringResource(Res.string.domains_prefix),
        ipsPrefix = stringResource(Res.string.ips_prefix),
        portPrefix = stringResource(Res.string.port_prefix),
        deleteLabel = stringResource(Res.string.delete),
        backLabel = stringResource(Res.string.edit_back_cd),
        unknownLabel = stringResource(Res.string.unknown),
    )

@Composable
fun rememberSettingsUiLabels(): SettingsUiLabels =
    SettingsUiLabels(
        title = stringResource(Res.string.settings_title),
        generalSectionTitle = stringResource(Res.string.general_part),
        networkSectionTitle = stringResource(Res.string.network_part),
        themeTitle = stringResource(Res.string.theme_select),
        themeDescription = stringResource(Res.string.dark_mode_description),
        lightModeLabel = stringResource(Res.string.light_mode),
        darkModeLabel = stringResource(Res.string.dark_mode),
        autoModeLabel = stringResource(Res.string.auto_mode),
        bootAutoStartTitle = stringResource(Res.string.boot_auto_start),
        bootAutoStartDescription = stringResource(Res.string.boot_auto_start_desc),
        agentFunctionsTitle = stringResource(Res.string.agent_functions_title),
        agentFunctionsDescription = stringResource(Res.string.agent_functions_desc),
        hideFromRecentsTitle = stringResource(Res.string.hide_from_recents_title),
        hideFromRecentsDescription = stringResource(Res.string.hide_from_recents_desc),
        lanSocksProxyTitle = stringResource(Res.string.lan_socks_proxy_title),
        lanSocksProxyDescription = stringResource(Res.string.lan_socks_proxy_desc),
        lanHttpProxyTitle = stringResource(Res.string.lan_http_proxy_title),
        lanHttpProxyDescription = stringResource(Res.string.lan_http_proxy_desc),
        subscriptionSectionTitle = stringResource(Res.string.subscription_part),
        sendHwidTitle = stringResource(Res.string.send_hwid),
        sendHwidDescription = stringResource(Res.string.send_hwid_desc),
        httpProxyPortTitle = stringResource(Res.string.http_proxy_port),
        socksPortTitle = stringResource(Res.string.socks_port),
        socksUsernameTitle = stringResource(Res.string.socks_username_title),
        socksPasswordTitle = stringResource(Res.string.socks_password_title),
        dnsIpv4Title = stringResource(Res.string.dns_ipv4),
        enableIpv6Title = stringResource(Res.string.enable_ipv6),
        enableIpv6Description = stringResource(Res.string.enable_ipv6_description),
        dnsIpv6Title = stringResource(Res.string.dns_ipv6),
        editDialogTitle = stringResource(Res.string.edit),
        saveLabel = stringResource(Res.string.save),
        cancelLabel = stringResource(Res.string.cancel),
        cannotBeEmpty = stringResource(Res.string.can_not_be_empty),
        portInvalid = stringResource(Res.string.err_port_invalid),
        ipv4Empty = stringResource(Res.string.err_ipv4_empty),
        ipv4ItemEmpty = stringResource(Res.string.err_ipv4_item_empty),
        ipv4Invalid = stringResource(Res.string.err_ipv4_invalid),
        ipv4Duplicate = stringResource(Res.string.err_ipv4_duplicate),
        ipv6Empty = stringResource(Res.string.err_ipv6_empty),
        ipv6ItemEmpty = stringResource(Res.string.err_ipv6_item_empty),
        ipv6Invalid = stringResource(Res.string.err_ipv6_invalid),
        ipv6Duplicate = stringResource(Res.string.err_ipv6_duplicate),
        socksUsernameEmpty = stringResource(Res.string.err_socks_user_empty),
        socksPasswordEmpty = stringResource(Res.string.err_socks_pass_empty),
        socksLengthExceeded = stringResource(Res.string.err_socks_length_exceeded),
        socksInvalidChars = stringResource(Res.string.err_socks_invalid_chars),
        scanQrLabel = stringResource(Res.string.scan_qr_title),
        qrScannerTitle = stringResource(Res.string.scan_qr_title),
        qrPermissionRequired = stringResource(Res.string.scan_qr_permission_desc),
        aboutSectionTitle = stringResource(Res.string.about_part),
        appVersionTitle = stringResource(Res.string.xrayfa_version),
        hwidTitle = stringResource(Res.string.hwid),
        xrayCoreVersionTitle = stringResource(Res.string.xray_core_version),
        repoTitle = stringResource(Res.string.repo_site),
        repoDescription = stringResource(Res.string.repo_description),
        unknownLabel = stringResource(Res.string.unknown),
        subscriptionUrlCopied = stringResource(Res.string.copied),
        platformSectionTitle = stringResource(Res.string.platform_section),
        appsTitle = stringResource(Res.string.allow_app_settings),
        appsDescription = stringResource(Res.string.select_app_settings),
        logcatTitle = stringResource(Res.string.logcat),
        logcatDescription = stringResource(Res.string.logcat_desc),
        routeSettingsTitle = stringResource(Res.string.route_settings_title),
        routeSettingsDescription = stringResource(Res.string.route_settings_desc),
        platformUnavailableDescription = stringResource(Res.string.platform_unavailable),
        appsInfoTitle = stringResource(Res.string.allow_app_settings),
        appsInfoMessage = stringResource(Res.string.apps_info_message),
        appsConfiguredSummary = stringResource(Res.string.apps_configured_summary),
        appsNoPackagesMessage = stringResource(Res.string.apps_no_packages),
        appsSearchLabel = stringResource(Res.string.apps_search),
        appsClearAllLabel = stringResource(Res.string.apps_clear_all),
        appLogEmptyMessage = stringResource(Res.string.no_log_text),
        appLogClearLabel = stringResource(Res.string.app_log_clear),
        appLogCopyLabel = stringResource(Res.string.app_log_copy),
        geoLiteTitle = stringResource(Res.string.geo_lite_title),
        geoLiteDescription = stringResource(Res.string.geo_ip_lite_description),
        geoDownloadNeedServiceHint = stringResource(Res.string.geo_download_need_service_hint),
        geoLiteDownloadUnavailableHint = stringResource(Res.string.geo_lite_download_unavailable),
        delayTestUrlTitle = stringResource(Res.string.test_url),
    )
