package com.android.xrayfa.shared.ui.settings

data class RouteSettingsUiLabels(
    val title: String = "Route settings",
    val routingModeSectionTitle: String = "Routing Mode",
    val routingModeGlobalLabel: String = "Global Mode",
    val routingModeRouteLabel: String = "Route Mode",
    val domainStrategySectionTitle: String = "Domain Strategy",
    val domainStrategyAsIsLabel: String = "AsIs",
    val domainStrategyIpIfNonMatchLabel: String = "IPIfNonMatch",
    val domainStrategyIpOnDemandLabel: String = "IPOnDemand",
    val strategyFieldLabel: String = "Strategy",
    val quickConfigSectionTitle: String = "Quick Config Presets",
    val bypassChinaLabel: String = "Bypass Mainland China",
    val bypassChinaDescription: String = "geosite:cn, geoip:cn -> Direct",
    val proxyTelegramGoogleLabel: String = "Proxy Telegram & Google",
    val proxyTelegramGoogleDescription: String = "geosite:telegram, geosite:google -> Proxy",
    val blockAdsLabel: String = "Block Ads",
    val blockAdsDescription: String = "geosite:category-ads-all -> Block",
    val customRulesSectionTitle: String = "Custom Routing Rules",
    val addCustomRuleLabel: String = "Add Custom Rule",
    val createCustomRuleTitle: String = "Create Custom Rule",
    val ruleNameLabel: String = "Rule Name / Tag (Optional)",
    val outboundTagLabel: String = "Outbound Tag (proxy/direct/block)",
    val domainsLabel: String = "Domains (comma separated)",
    val ipsLabel: String = "IPs (comma separated)",
    val portLabel: String = "Port (e.g., 53, 1-1024)",
    val confirmAddLabel: String = "Confirm and Add",
    val customRuleFallbackTitle: String = "Custom Rule",
    val outboundTagShortLabel: String = "Outbound Tag",
    val domainsPrefix: String = "Domains:",
    val ipsPrefix: String = "IPs:",
    val portPrefix: String = "Port:",
    val deleteLabel: String = "Delete",
    val backLabel: String = "Back",
    val unknownLabel: String = "Unknown",
)
