package com.android.xrayfa.shared.ui.config

data class ConfigUiLabels(
    val title: String = "Config",
    val manualFilterLabel: String = "Manual",
    val allFilterLabel: String = "All",
    val favoriteFilterLabel: String = "Favorite",
    val emptyTitle: String = "No configuration",
    val emptyHint: String = "Add a node to get started",
    val createConfigLabel: String = "Create configuration",
    val unknownProtocolLabel: String = "Unknown",
    val timeoutLabel: String = "Timeout",
    val testingLabel: String = "Testing...",
    val addToFavoritesLabel: String = "Add to favorites",
    val removeFromFavoritesLabel: String = "Remove from favorites",
    val testDelayLabel: String = "Test delay",
    val shareLabel: String = "Share",
    val editLabel: String = "Edit",
    val deleteLabel: String = "Delete",
    val editNodeTitle: String = "Edit node",
    val nodeRemarkLabel: String = "Remark",
    val nodeUrlLabel: String = "Node URL",
    val saveLabel: String = "Save",
    val cancelLabel: String = "Cancel",
    val editNodeFailed: String = "Failed to save node. Check the URL.",
    val deleteNodeTitle: String = "Delete node",
    val deleteNodeConfirm: String = "Delete this node?",
)
